from enum import Enum


class BloomEnum(Enum):
    JPEASIUS = ("JPEASIUS", "美国JP经济惊喜指数", "JPMorgan经济惊喜指数", "美国")
    JPEASIEU = ("JPEASIEU", "欧元区JP经济惊喜指数", "JPMorgan经济惊喜指数", "欧元区")
    JPEASIAU = ("JPEASIAU", "澳洲JP经济惊喜指数", "JPMorgan经济惊喜指数", "澳洲")
    JPEASIJP = ("JPEASIJP", "日本JP经济惊喜指数", "JPMorgan经济惊喜指数", "日本")
    JPEASISZ = ("JPEASISZ", "瑞士JP经济惊喜指数", "JPMorgan经济惊喜指数", "瑞士")
    JPEASIUK = ("JPEASIUK", "英国JP经济惊喜指数", "JPMorgan经济惊喜指数", "英国")
    JPEASICA = ("JPEASICA", "加拿大JP经济惊喜指数", "JPMorgan经济惊喜指数", "加拿大")
    JPEASINZ = ("JPEASINZ", "新西兰JP经济惊喜指数", "JPMorgan经济惊喜指数", "新西兰")

    JFRIUS = ("JFRIUS", "美国JP预测修正指数", "JPMorgan预测修正指数", "美国")
    JFRIEURO = ("JFRIEURO", "欧元区JP预测修正指数", "JPMorgan预测修正指数", "欧元区")
    JFRIAU = ("JFRIAU", "澳洲JP预测修正指数", "JPMorgan预测修正指数", "澳洲")
    JFRIJP = ("JFRIJP", "日本JP预测修正指数", "JPMorgan预测修正指数", "日本")
    JFRICN = ("JFRICN", "瑞士JP预测修正指数", "JPMorgan预测修正指数", "瑞士")
    JFRIGB = ("JFRIGB", "英国JP预测修正指数", "JPMorgan预测修正指数", "英国")
    JFRICA = ("JFRICA", "加拿大JP预测修正指数", "JPMorgan预测修正指数", "加拿大")

    CESIUSD = ("CESIUSD", "美国CITI经济惊喜指数", "CITI经济惊喜指数", "美国")
    CESIEUR = ("CESIEUR", "欧元区CITI经济惊喜指数", "CITI经济惊喜指数", "欧元区")
    CESIGBP = ("CESIGBP", "英国CITI经济惊喜指数", "CITI经济惊喜指数", "英国")
    CESIJPY = ("CESIJPY", "日本CITI经济惊喜指数", "CITI经济惊喜指数", "日本")
    CESICAD = ("CESICAD", "加拿大CITI经济惊喜指数", "CITI经济惊喜指数", "加拿大")
    CESIAUD = ("CESIAUD", "澳洲CITI经济惊喜指数", "CITI经济惊喜指数", "澳洲")
    CESINZD = ("CESINZD", "新西兰CITI经济惊喜指数", "CITI经济惊喜指数", "新西兰")
    CESICHF = ("CESICHF", "瑞士CITI经济惊喜指数", "CITI经济惊喜指数", "瑞士")

    CTOTUSD = ("CTOTUSD", "美国CITI贸易条件指数", "CITI贸易条件指数", "美国")
    CTOTAUD = ("CTOTAUD", "澳洲CITI贸易条件指数", "CITI贸易条件指数", "澳洲")
    CTOTNZD = ("CTOTNZD", "新西兰CITI贸易条件指数", "CITI贸易条件指数", "新西兰")
    CTOTCAD = ("CTOTCAD", "加拿大CITI贸易条件指数", "CITI贸易条件指数", "加拿大")
    CTOTJPY = ("CTOTJPY", "日本CITI贸易条件指数", "CITI贸易条件指数", "日本")
    CTOTEUR = ("CTOTEUR", "欧元区CITI贸易条件指数", "CITI贸易条件指数", "欧元区")
    CTOTGBP = ("CTOTGBP", "英国CITI贸易条件指数", "CITI贸易条件指数", "英国")

    CECIDUSD = ("CECIDUSD", "美国CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "美国")
    CECIDEUR = ("CECIDEUR", "欧元区CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "欧元区")
    CECIUAUD = ("CECIUAUD", "澳洲CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "澳洲")
    CECIUCAD = ("CECIUCAD", "加拿大CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "加拿大")
    CECIUCHF = ("CECIUCHF", "瑞士CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "瑞士")
    CECIUGBP = ("CECIUGBP", "英国CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "英国")
    CECIUJPY = ("CECIUJPY", "日本CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "日本")
    CECIUNZD = ("CECIUNZD", "新西兰CITI经济预测不确定性指数", "CITI经济预测不确定性指数", "新西兰")

    EUR001M = ("EUR001M", "欧元区1M基准利率", "短期基准利率", "欧元区")
    TISONI1M = ("TISONI1M", "英国1M基准利率", "短期基准利率", "英国")
    TI0001M = ("TI0001M", "日本1M基准利率", "短期基准利率", "日本")
    TCOR1M = ("TCOR1M", "加拿大1M基准利率", "短期基准利率", "加拿大")
    BBSW1M = ("BBSW1M", "澳洲1M基准利率", "短期基准利率", "澳洲")
    NDBB1M = ("NDBB1M", "新西兰1M基准利率", "短期基准利率", "新西兰")
    SARO1MC = ("SARO1MC", "瑞士1M基准利率", "短期基准利率", "瑞士")
    TSFR1M = ("TSFR1M", "美国1M基准利率", "短期基准利率", "美国")

    ECOCEAS = ("ECOCEAS", "欧元区经常账户差额", "经常账户差额", "欧元区")
    ECOCUKS = ("ECOCUKS", "英国经常账户差额", "经常账户差额", "英国")
    ECOCJPN = ("ECOCJPN", "日本经常账户差额", "经常账户差额", "日本")
    ECOCCAS = ("ECOCCAS", "加拿大经常账户差额", "经常账户差额", "加拿大")
    ECOCAUS = ("ECOCAUS", "澳洲经常账户差额", "经常账户差额", "澳洲")
    ECOCNZN = ("ECOCNZN", "新西兰经常账户差额", "经常账户差额", "新西兰")
    ECOCCHN = ("ECOCCHN", "瑞士经常账户差额", "经常账户差额", "瑞士")
    ECOCUSS = ("ECOCUSS", "美国经常账户差额", "经常账户差额", "美国")

    OE19CFAA = ("OE19CFAA", "欧元区FDI", "FDI", "欧元区")
    FDNVGBR = ("FDNVGBR", "英国FDI", "FDI", "英国")
    FDIVJPN = ("FDIVJPN", "日本FDI", "FDI", "日本")
    FDIVCAN = ("FDIVCAN", "加拿大FDI", "FDI", "加拿大")
    FDNVAUS = ("FDNVAUS", "澳洲FDI", "FDI", "澳洲")
    FDNVNZL = ("FDNVNZL", "新西兰FDI", "FDI", "新西兰")
    FDNVCHE = ("FDNVCHE", "瑞士FDI", "FDI", "瑞士")
    FDIITOTL = ("FDIITOTL", "美国FDI", "FDI", "美国")

    CPEXEMUY = ("CPEXEMUY", "欧元区核心CPI", "CPI", "欧元区")
    UKHCA9IQ = ("UKHCA9IQ", "英国核心CPI", "CPI", "英国")
    JCPNEFFE = ("JCPNEFFE", "日本核心CPI", "CPI", "日本")
    EHPICAY = ("EHPICAY", "加拿大核心CPI", "CPI", "加拿大")
    AUCCDLFI = ("AUCCDLFI", "澳洲核心CPI", "CPI", "澳洲")
    NZICSFYT = ("NZICSFYT", "新西兰核心CPI", "CPI", "新西兰")
    SZEXIYOY = ("SZEXIYOY", "瑞士核心CPI", "CPI", "瑞士")
    CPIXYOY = ("CPI XYOY", "美国核心CPI", "CPI", "美国")

    INDU = ("INDU", "道琼斯指数", "股指价格", "美国")
    CCMP = ("CCMP", "纳斯达克指数", "股指价格", "美国")
    SPX = ("SPX", "标普指数", "股指价格", "美国")
    DAX = ("DAX", "德国DAX指数", "股指价格", "德国")
    UKX = ("UKX", "英国富时100指数", "股指价格", "英国")
    NKY = ("NKY", "日经225指数", "股指价格", "日经")
    SPTSX = ("SPTSX", "加拿大TSX综合指数", "股指价格", "加拿大")
    AS51 = ("AS51", "澳证200指数", "股指价格", "澳洲")
    NZSE50FG = ("NZSE50FG", "新西兰标普50指数", "股指价格", "新西兰")
    SMI = ("SMI", "瑞士市场指数", "股指价格", "瑞士")

    EURUSDV1M = ("EURUSDV1M", "EURUSD1mATM期权波动率", "1m期权波动率", "欧元区")
    GBPUSDV1M = ("GBPUSDV1M", "GBPUSD1mATM期权波动率", "1m期权波动率", "英国")
    USDJPYV1M = ("USDJPYV1M", "USDJPY1mATM期权波动率", "1m期权波动率", "日本")
    USDCADV1M = ("USDCADV1M", "USDCAD1mATM期权波动率", "1m期权波动率", "加拿大")
    AUDUSDV1M = ("AUDUSDV1M", "AUDUSD1mATM期权波动率", "1m期权波动率", "澳洲")
    NZDUSDV1M = ("NZDUSDV1M", "NZDUSD1mATM期权波动率", "1m期权波动率", "新西兰")
    USDCHFV1M = ("USDCHFV1M", "USDCHF1mATM期权波动率", "1m期权波动率", "瑞士")

    EURUSDV3M = ("EURUSDV3M", "EURUSD3mATM期权波动率", "3m期权波动率", "欧元区")
    GBPUSDV3M = ("GBPUSDV3M", "GBPUSD3mATM期权波动率", "3m期权波动率", "英国")
    USDJPYV3M = ("USDJPYV3M", "USDJPY3mATM期权波动率", "3m期权波动率", "日本")
    USDCADV3M = ("USDCADV3M", "USDCAD3mATM期权波动率", "3m期权波动率", "加拿大")
    AUDUSDV3M = ("AUDUSDV3M", "AUDUSD3mATM期权波动率", "3m期权波动率", "澳洲")
    NZDUSDV3M = ("NZDUSDV3M", "NZDUSD3mATM期权波动率", "3m期权波动率", "新西兰")
    USDCHFV3M = ("USDCHFV3M", "USDCHF3mATM期权波动率", "3m期权波动率", "瑞士")

    EURUSD = ("EURUSD BGN", "EURUSD即期汇率", "即期汇率", "欧元区")
    GBPUSD = ("GBPUSD BGN", "GBPUSD即期汇率", "即期汇率", "英国")
    USDJPY = ("USDJPY BGN", "USDJPY即期汇率", "即期汇率", "日本")
    USDCAD = ("USDCAD BGN", "USDCAD即期汇率", "即期汇率", "加拿大")
    AUDUSD = ("AUDUSD BGN", "AUDUSD即期汇率", "即期汇率", "澳洲")
    NZDUSD = ("NZDUSD BGN", "NZDUSD即期汇率", "即期汇率", "新西兰")
    USDCHF = ("USDCHF BGN", "USDCHF即期汇率", "即期汇率", "瑞士")
    USDCNH = ("USDCNH BGN", "USDCNH即期汇率", "即期汇率", "中国")

    IOEA = ("IOEA Comdty", "中国铁矿石期货主力合约价格", "期货主力合约价格", "中国")
    CUA = ("CUA Comdty", "中国沪铜期货主力合约价格", "期货主力合约价格", "中国")
    SAIA = ("SAIA Comdty", "中国沪银期货主力合约价格", "期货主力合约价格", "中国")
    AUAA = ("AUAA Comdty", "中国黄金期货主力合约价格", "期货主力合约价格", "中国")
    LHDA = ("LHDA Comdty", "中国生猪期货主力合约价格", "期货主力合约价格", "中国")
    RBTA = ("RBTA Comdty", "中国螺纹钢期货主力合约价格", "期货主力合约价格", "中国")
    SCPA = ("SCPA Comdty", "中国原油期货主力合约价格", "期货主力合约价格", "中国")
    FOA = ("FOA Comdty", "中国燃油期货主力合约价格", "期货主力合约价格", "中国")
    AAA = ("AAA Comdty", "中国沪铝期货主力合约价格", "期货主力合约价格", "中国")
    FGLA = ("FGLA Comdty", "中国玻璃期货主力合约价格", "期货主力合约价格", "中国")
    PVCA = ("PVCA Comdty", "中国PVC期货主力合约价格", "期货主力合约价格", "中国")
    CKCA = ("CKCA Comdty", "中国焦煤期货主力合约价格", "期货主力合约价格", "中国")
    SHYA = ("SHYA Comdty", "中国纯碱期货主力合约价格", "期货主力合约价格", "中国")
    ZNAA = ("ZNAA Comdty", "中国沪锌期货主力合约价格", "期货主力合约价格", "中国")
    IFDA = ("IFDA Index", "中证1000股指期货主力合约价格", "期货主力合约价格", "中国")
    FFDA = ("FFDA Index", "中证500股指期货主力合约价格", "期货主力合约价格", "中国")
    IFBA = ("IFBA Index", "沪深300股指期货主力合约价格", "期货主力合约价格", "中国")
    FFBA = ("FFBA Index", "上证50股指期货主力合约价格", "期货主力合约价格", "中国")
    TBSA = ("TBSA Comdty", "中国30年期国债期货主力合约价格", "期货主力合约价格", "中国")
    TFTA = ("TFTA Comdty", "中国10年期国债期货主力合约价格", "期货主力合约价格", "中国")
    TFCA = ("TFCA Comdty", "中国5年期国债期货主力合约价格", "期货主力合约价格", "中国")

    USDCNHV1W = ("USDCNHV1W", "USDCNH 1周平值隐含波动率", "期权波动率指标", "中国")
    USDCNHV3M = ("USDCNHV3M", "USDCNH 3月平值隐含波动率", "期权波动率指标", "中国")
    USDCNH25RON = ("USDCNH25RON", "USDCNH 隔夜 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R1W = ("USDCNH25R1W", "USDCNH 1周 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R2W = ("USDCNH25R2W", "USDCNH 2周 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R3W = ("USDCNH25R3W", "USDCNH 3周 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R1M = ("USDCNH25R1M", "USDCNH 1个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R2M = ("USDCNH25R2M", "USDCNH 2个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R3M = ("USDCNH25R3M", "USDCNH 3个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R4M = ("USDCNH25R4M", "USDCNH 4个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R6M = ("USDCNH25R6M", "USDCNH 6个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R9M = ("USDCNH25R9M", "USDCNH 9个月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R1Y = ("USDCNH25R1Y", "USDCNH 1年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R18M = ("USDCNH25R18M", "USDCNH 1年6月 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R2Y = ("USDCNH25R2Y", "USDCNH 2年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R3Y = ("USDCNH25R3Y", "USDCNH 3年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R4Y = ("USDCNH25R4Y", "USDCNH 4年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R5Y = ("USDCNH25R5Y", "USDCNH 5年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R7Y = ("USDCNH25R7Y", "USDCNH 7年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH25R10Y = ("USDCNH25R10Y", "USDCNH 10年 25 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH35R3M = ("USDCNH35R3M", "USDCNH 3个月 35 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH15R3M = ("USDCNH15R3M", "USDCNH 3个月 15 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH10R3M = ("USDCNH10R3M", "USDCNH 3个月 10 Delta风险逆转指标", "期权波动率指标", "中国")
    USDCNH35B3M = ("USDCNH35B3M", "USDCNH 3个月 35 蝶式套利", "期权波动率指标", "中国")
    USDCNH25B3M = ("USDCNH25B3M", "USDCNH 3个月 25 蝶式套利", "期权波动率指标", "中国")
    USDCNH15B3M = ("USDCNH15B3M", "USDCNH 3个月 15 蝶式套利", "期权波动率指标", "中国")
    USDCNH10B3M = ("USDCNH10B3M", "USDCNH 3个月 10 蝶式套利", "期权波动率指标", "中国")

    CNYRINDX = ("CNYRINDX", "CFETS人民币指数", "货币指数", "中国")

    @classmethod
    def get_element(cls, target):
        for member in cls:
            if member.value[0] in target:
                return member
        return None
